### ISSUE TITLE
Add a default value to optional params

### ISSUE THREAD

**Issue by cyrilchampier** [julien-meichelbeck/partial_parameters#1]
I can do it if you want ?

```
- partial_parameters
  - required(:form)
  - optional(:relative, false)
```

**Comment by cyrilchampier** [comment]
from @julien-meichelbeck 

> Hey j'y avais pensé mais c'est pas cohérent avec le faire que cette gem n'a aucun impact en production. Elle balance des erreurs en test et dev. On peut en discuter vendredi si tu veux quand je reviens

**Comment by cyrilchampier** [comment]
I did know it did not have any impact on prod.
We prefer an undefined behavior over a 500 quickly detected by sentry ?

If we want to keep that behavior, I would be more inclined to play with the "strict" parameter:
in prod, its false by default, and only logs if an error occurs.

And default values would work in both cases

**Comment by julien-meichelbeck** [comment]
The first idea behind this gem was to warn if a partial is not used/documented properly. Just displaying a warning in the console or on the server would be inefficient because it wouldn't be be visible enough, that's why it throws an error. 
We could still revamp the gem and change its behavior!

**Comment by cyrilchampier** [comment]
k, lets close this for now, we will see if the need arise again
